---
# Keep base_vms hosts in sync with base_vms variable in group_vars/all.yml
all:
  children:
    hypervisors:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
    base_vms:
      hosts:
        vm-base-dev-onprem-01:
          ansible_host: 192.168.122.101
        vm-base-dev-onprem-02:
          ansible_host: 192.168.122.102
