---
# ===========================================================================
# Play 1 – Provision VMs on the local KVM hypervisor
# ===========================================================================
- name: Provision VMs on hypervisor
  hosts: hypervisors
  become: true
  gather_facts: true
  tags:
    - provision
  roles:
    - role: 01-hypervisor-setup
    - role: 02-vm-provisioning

# ===========================================================================
# Play 2 – Apply base hardening to all provisioned VMs
# ===========================================================================
- name: Apply base hardening to VMs
  hosts: vms
  become: true
  gather_facts: true
  tags:
    - hardening
  pre_tasks:
    - name: Wait for VM connectivity
      ansible.builtin.wait_for_connection:
        timeout: 300
        delay: 5
      tags:
        - always
  roles:
    - role: 03-common
      tags:
        - common
    - role: 04-ssh-hardening
      tags:
        - ssh
    - role: 05-firewall
      tags:
        - firewall
