---
collections:
  - name: ansible.posix
    version: "2.1.0"
  - name: community.general
    version: "12.3.0"
  - name: community.crypto
    version: "2.18.0"
  - name: community.libvirt
    version: "2.0.0"
  - name: devsec.hardening
    version: "10.5.0"
