---
# Play 1 – Create VMs on the local KVM hypervisor
- name: Provision VMs on hypervisor
  hosts: hypervisors
  become: true
  gather_facts: true
  tags:
    - provision
  roles:
    - role: 01-vm-create

# Play 2 – Apply base hardening to all provisioned VMs
- name: Apply base hardening to VMs
  hosts: vms
  become: true
  gather_facts: true
  tags:
    - hardening
  pre_tasks:
    - name: Wait for VM connectivity
      ansible.builtin.wait_for_connection:
        timeout: 300
        delay: 5
      tags:
        - always
  roles:
    - role: 02-common
      tags: [common]
    - role: 03-ssh-hardening
      tags: [ssh]
    - role: 04-firewall
      tags: [firewall]
