---
# ==============================================================================
# Play 1: Provision base VMs on KVM hypervisor
# ==============================================================================
- name: Provision base VMs on KVM hypervisor
  hosts: hypervisors
  become: true
  tags:
    - provision
  roles:
    - base-vms

# ==============================================================================
# Play 2: Harden base VMs (connects as admin user — fully idempotent)
# ==============================================================================
- name: Harden base VMs
  hosts: base_vms
  gather_facts: true
  become: true
  serial: 1
  tags:
    - hardening
  vars:
    _deployer: "{{ lookup('env', 'SUDO_USER') | default(lookup('env', 'USER'), true) }}"
    vm_keys_dir: "{{ vm_keys_base_dir }}/{{ _deployer }}/.ssh/vm-keys-{{ env }}"
    ansible_user: "{{ admin_user }}"
    ansible_ssh_private_key_file: "{{ vm_keys_dir }}/{{ inventory_hostname }}_id_ed25519"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'

  pre_tasks:
    - name: Wait for cloud-init to complete
      ansible.builtin.command:
        cmd: cloud-init status --wait
      register: cloud_init_result
      changed_when: false
      failed_when: cloud_init_result.rc not in [0, 2]
      timeout: 300

    - name: Remove root SSH authorized keys (defense-in-depth)
      ansible.builtin.file:
        path: /root/.ssh/authorized_keys
        state: absent

    - name: Display hardening information
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Hardening: {{ inventory_hostname }}"
          - "=========================================="
          - "IP: {{ ansible_host }}"
          - "User: {{ admin_user }}"
          - "=========================================="

  roles:
    - role: ssh-hardening
      tags: ['ssh-hardening']
    - role: os-hardening
      tags: ['os-hardening']
    - role: fail2ban
      tags: ['fail2ban']

  post_tasks:
    - name: Display hardening summary
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "Hardening Complete: {{ inventory_hostname }}"
          - "=========================================="
          - "SSH: ssh -i {{ vm_keys_dir }}/{{ inventory_hostname }}_id_ed25519 {{ admin_user }}@{{ ansible_host }}"
          - ""
          - "Applied:"
          - "  - SSH hardening (CIS/STIG-aligned, root login disabled)"
          - "  - OS hardening (kernel, filesystem, users)"
          - "  - Firewall (UFW, deny-all ingress + egress)"
          - "  - Fail2ban (SSH brute-force + recidive)"
          - "  - AIDE file integrity monitoring"
          - "  - Automatic security updates"
          - "  - Audit logging (CIS rules)"
          - "  - Root account locked"
          - "=========================================="

# ==============================================================================
# Play 3: Destroy VMs (only runs with --tags destroy)
# ==============================================================================
- name: Destroy base VMs
  hosts: hypervisors
  become: true
  tags:
    - never
    - destroy

  pre_tasks:
    - name: Determine actual user
      ansible.builtin.set_fact:
        actual_user: "{{ lookup('env', 'SUDO_USER') | default(lookup('env', 'USER'), true) }}"

    - name: Set SSH key directory
      ansible.builtin.set_fact:
        vm_keys_dir: "{{ vm_keys_base_dir }}/{{ actual_user }}/.ssh/vm-keys-{{ env }}"

    - name: Set target VMs for destruction
      ansible.builtin.set_fact:
        destroy_vms: "{{ target_vms | default([]) }}"

    - name: Fail if no target VMs specified
      ansible.builtin.fail:
        msg: >
          Specify target_vms to destroy.
          Example: -e 'target_vms=["vm-base-dev-onprem-01"]'
      when: destroy_vms | length == 0

  tasks:
    - name: Include destroy tasks
      ansible.builtin.include_role:
        name: base-vms
        tasks_from: destroy
