---
all:
  children:
    hypervisors:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
    vms:
      hosts:
        vm-base-dev-onprem-01:
          ansible_host: 192.168.122.11
        vm-base-dev-onprem-02:
          ansible_host: 192.168.122.12
        # ansible_ssh_private_key_file: "{{ ssh_deploy_key_file }}"
        # ansible_ssh_common_args: '-o ProxyJump=bastion'  # Uncomment for bastion
