---
all:
  children:
    openclaw:
      hosts:
        # vm-openclaw-dev-onprem-01:
        #   ansible_host: 192.168.1.20
      vars:
        ansible_user: deploy
        ansible_python_interpreter: /usr/bin/python3
        # ansible_ssh_private_key_file: "{{ ssh_deploy_key_file }}"
        # ansible_ssh_common_args: '-o ProxyJump=bastion'  # Uncomment for bastion
